apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:  
  - deployment.yaml
  - service.yaml
  - namespace.yaml
  - secret-sealed.yaml
  # - secret.enc.yaml  
  # - secret.yaml
# secretGenerator:
#   - name: sqlserver-connection-string
#     type: Opaque
#     literals:
#       - password=Server=tour-of-heroes-sql,1433;Initial Catalog=heroes;Persist Security Info=False;User ID=sa;Password=YourStrong!Passw0rd;